// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTwdiibLkiPfeoTUvuuYTovC69BAlfEOI',
    appId: '1:66718680345:web:dd0df2b49067e41b43f188',
    messagingSenderId: '66718680345',
    projectId: 'fooddeliveryapp-9b09f',
    authDomain: 'fooddeliveryapp-9b09f.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-9b09f.appspot.com',
    measurementId: 'G-0Z6R6ZDZ8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdPyhy64PaWWWD5JbXb3C1E7QV_W4Rrns',
    appId: '1:66718680345:android:440624c1d1cf81c043f188',
    messagingSenderId: '66718680345',
    projectId: 'fooddeliveryapp-9b09f',
    storageBucket: 'fooddeliveryapp-9b09f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAXG8hqVEZdPXM_1HruzU-nuSmqZxuFrw',
    appId: '1:66718680345:ios:f6beb3a50f21355543f188',
    messagingSenderId: '66718680345',
    projectId: 'fooddeliveryapp-9b09f',
    storageBucket: 'fooddeliveryapp-9b09f.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAXG8hqVEZdPXM_1HruzU-nuSmqZxuFrw',
    appId: '1:66718680345:ios:8afb64bdadc9810c43f188',
    messagingSenderId: '66718680345',
    projectId: 'fooddeliveryapp-9b09f',
    storageBucket: 'fooddeliveryapp-9b09f.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp.RunnerTests',
  );
}
